### ISSUE TITLE
Research mapping tools and integration with city data

### ISSUE THREAD

**Issue by ximsce** [CodeForBoulder/c3po#11]
Research the effort required and the mapping tools available for displaying a map using the city's available data.

Things to keep in mind:
1.  Effort required to develop
2.  Difficulty of using in an app vs responsive website
3.  Cost

**Comment by ManUnderhill** [comment]
Prototyped with Google Maps API. Dan and I concluded that the CartoDB API can do more with less coding, so Dan has Forked the repo for a sandbox where he can figure out how we can use CartoDB.
