### ISSUE TITLE
Login/Profile

### ISSUE THREAD

**Issue by cellisco** [CodeForBoulder/c3po#2]
Create the profile "schema"
Identify minimum required attributes
Create simple crud page

**Comment by ximsce** [comment]
Login Creds: facebook, twitter, or email linked to screenname
Optional attributes: address, sms, notification radius

**Comment by lmnleaf** [comment]
Waiting for Facebook credentials. Tutorials for setting up Facebook login in Rails app: http://railscasts.com/episodes/360-facebook-authentication?view=asciicast and http://agelber.com/blog/adding-facebook-auth-to-rails/

**Comment by ximsce** [comment]
We can create a facebook page with the email address c3po@codeforboulder.org

**Comment by ximsce** [comment]
I tried out the 'devise' module for profile management.  It seemed pretty open ended and configurable.  I recommend it unless someone else knows of a better one.

**Comment by ManUnderhill** [comment]
Created FB login using one line in html and a couple css lines for alignment. (Meteor branch)

**Comment by wheresmypen** [comment]
Seems deprecated to me.
