### ISSUE TITLE
Facebook comment integration

### ISSUE THREAD

**Issue by ximsce** [CodeForBoulder/c3po#3]
Allow users to participate in development specific conversations through facebook (with or without their own facebook account)

**Comment by ximsce** [comment]
First steps: spike the capabilities that facebook actually provides and what that might look like within our ui - login, post a comment (w/fb account, w/o fb account), push a notification

**Comment by lmnleaf** [comment]
Create test users.

**Comment by wheresmypen** [comment]
Using disqus
